### PR TITLE
merge arm builds with docker manifest

### PR DESCRIPTION
**Pull request by minrk**
instead of creating a new tag, so we have true multi-arch builds

following https://docs.docker.com/engine/reference/commandline/manifest/

### CODE REVIEW

**Comment by minrk** [comment]
I ran this merge command manually with the published artifacts for 2012-12-12, so that's now a [true multi-arch build](https://github.com/scientificcomputing/packages/pkgs/container/fenics/58380863?tag=2022-12-12). This should make it automatic from now on, and remove the need for the `-arm` suffix.

**Comment by minrk** [comment]
Hm, one step I missed when testing locally is that I merged two _published_ manifests. You don't appear to be able to merge with a local manifest...Not sure why, yet.

**Comment by jorgensd** [comment]
Should we just merge this, or are we still experimenting?

**Comment by minrk** [comment]
Still experimenting. It's not pressing, really. Need to make changes:

1. deploy a localhost registry on circleCI (`docker run -d -p5000:5000 registry:2`)
2. push arm build to localhost registry
3. merge
4. push back to GHA

**Comment by minrk** [comment]
This works now!

Turns out manifest merge is very picky. It can only merge manifests _already published to the same registry_. That means we have to _push_ the arm builds to ghcr before merging them with the amd64 builds. Since you can't really delete tags from a docker registry, I elected to use a private _package_ for these temporary manifests, called [arm-manifests](https://github.com/orgs/scientificcomputing/packages/container/package/arm-manifests). There they can at least be ignored, if not deleted (we can delete the whole package periodically, if we want - it shouldn't take up any space, though, as it only contains tagged images also in other packages on the registry).

Latest run was [this one](https://github.com/scientificcomputing/packages/actions/runs/4063047216), which launched [this circleci job](https://app.circleci.com/pipelines/github/scientificcomputing/packages/60) and ultimately published the multi-arch [ghcr.io/scientificcomputing/ci-test:pr5-dd91cf036](https://github.com/scientificcomputing/packages/pkgs/container/ci-test/67352939?tag=pr5-dd91cf036).

**Pull request merged**
